sf tests: no need to check mlxconfig
Checking mlxconfig is taking some time and is redundant.
If mlxconfig is not configured for SFs the user gets an error anyway.
Error: mlx5_core: Port add is only supported in eswitch switchdev mode or SF ports are disabled.

Change-Id: Ide9b808e022e2c61dd1d445dbca53150df491f3f
Signed-off-by: Roi Dayan <roid@nvidia.com>