test-ovs-dpdk-vxlan-meter.sh: Fix doca meter.
The test was failing with DOCA:

ERROR: Number of filtered rules expected to be same as offloaded rules.
15:23:52 | Unexpected rules:
ufid:ef0050d9-2368-494d-9fae-5b283c21d203, skb_priority(0/0),skb_mark(0/0),ct_state(0/0),ct_zone(0/0),ct_mark(0/0),ct_label(0/0),recirc_id(0),dp_hash(0/0),in_port(ib_pf0),packet_type(ns=0,id=0),eth(src=66:82:82:54:ac:bf,dst=e4:96:3d:08:00:02),eth_type(0x0800),ipv4(src=1.1.1.8/0.0.0.0,dst=1.1.1.7/0.0.0.0,proto=1/0,tos=0/0,ttl=64/0,frag=no),icmp(type=0/0,code=0/0), packets:0, bytes:0, used:never, dp:ovs, actions:br-phy, dp-extra-info:miniflow_bits(5,1)

The packet came from PF w/o proper encap, which could happen due to the
meter dropping some of the tunnel discovery packets because they
exceeded the meter rate.

Fix by using default burst size parameter for the meter.

Same fix is applied to ovs-dpdk-tests/test-ovs-dpdk-meter.sh

Issue: 3640512
Change-Id: I05eec8b0142f6453548e2fbb03f0a67412ce85b0
Signed-off-by: Dima Chumak <dchumak@nvidia.com>