common-dpdk.sh: query_sw_packets_in_sent_packets_percentage(): Add missing argument
Make sure to add missing bridge arg for get_total_packets_passed()
to avoid the following error:
    ovs-ofctl: 'dump-flows' command requires at least 1 arguments
    ERROR: Cannot get pkts
    ERROR: Cannot get all_packets_passed

Change-Id: If5ad0006c9e4c1450e4feb8ee1d2f7e3288655f4
Signed-off-by: Mahmoud AbuZant <mahmoudabuz@nvidia.com>