test-eswitch-modes-sf.sh: Adapt expected error msg
Creating SFs in legacy mode is not supported but the given error msg
might change so the test was modified to accept old/new error msg.

Old msg:
Error: mlx5_core: Port add is only supported in eswitch switchdev mode

New msg:
Error: mlx5_core: SF ports are only supported in eswitch switchdev mode

Issue: 3586916
Signed-off-by: Ziyad Atiyyeh <ziyadat@nvidia.com>
Change-Id: Ie4e7a1d69a994813ff9e081c4dded1100b04d7fa