test-tc-insert-rules-ct-clear-waste.sh: Test mirred instead of drop
Error: mlx5_core: Drop with modify header action is not supported.

Change-Id: Ifd6c26be5619d69f0e329655f2e1a2b8e6c639bd
Signed-off-by: Roi Dayan <roid@nvidia.com>