test-ovs-ct-tcp-restore.sh: Fix iperf issue
Iperf 2 may take long time to initialize which sometimes causes [0] on
debug kernels. Use iperf3 instead. Also run iperf for longer.

[0]:
* sniff 200 software packets on enp8s0f0_0 to /tmp/dump
dropped privs to tcpdump
tcpdump: listening on enp8s0f0_0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
[ ID] Interval       Transfer     Bandwidth
[  1] 0.00-10.90 sec   397 KBytes   299 Kbits/sec
2 packets captured
3 packets received by filter
0 packets dropped by kernel
ERROR: Failed to catch 200 packets in software
wait for dying to be removed from list
* verify nf conntrack counter
runtime: 52s
TEST FAILED

Issue: 3171459
Change-Id: Ic9c910d879344380d5d5a4b94b243718e648a6ad
Signed-off-by: Vlad Buslov <vladbu@nvidia.com>