test-eswitch-modes-sf.sh: Update expected error msg
Update expected error msg while creating SF in legacy
mode which is unsupported.

Old msg:
Error: mlx5_core: Port add is only supported in eswitch switchdev mode

New msg:
Error: mlx5_core: SF ports are only supported in eswitch switchdev mode

Issue: 3586916
Signed-off-by: Ziyad Atiyyeh <ziyadat@nvidia.com>
Change-Id: I218a766e62641ce53370e160813ed9ae66285324