test-ovs-ct-tcp-restore.sh: Manually check for dying connections
Obtaining total connections count with "conntrack -C" command and comparing
it to number of lines resulting from "conntrack -L" command is inherently
racy since conntrack state can change concurrently in between these
commands, which leads to false-positives [0]. Moreover, the check is not
directly related to test purpose and was added for an unrelated bug. As
such, fix the issue by manually greping for dying connection with expected
tuple after flushing the conntrack table and waiting for 3 seconds.

[0]:
* verify nf conntrack counter
ERROR: Expected conntrack dump to match conntrack table count, diff 17, dumping dying table to see if connection is there
* verify conntrack dying table
conntrack v1.4.5 (conntrack-tools): 0 flow entries have been shown.
ERROR: Tuple is stuck in dying phase

Issue: 3171459
Change-Id: Icfc63c22214beea09ccb67e55ac28e6f0641dadf
Signed-off-by: Vlad Buslov <vladbu@nvidia.com>