semver.py: Fix comparing string builds
Example setting min kernel to 5.12 and comparing kernel
version 5.12.0_net_next_5e0ee70
TypeError: '<' not supported between instances of 'str' and 'int'

Expect string only in build or patch fields.

Change-Id: If2f89c901c53626117365a0ca5286a4cf440488b
Signed-off-by: Roi Dayan <roid@nvidia.com>