test-tc-vxlan-ct-sample.sh: Fix iperf code
Iperf 2 with '-t' flag sometimes takes significant amount of time to
initialize and client can't connect to it after two seconds timeout [0].
Fix the issue by refactoring the code to use iperf3. Parse the output with
jq tool since iperf3 doesn't support CSV output format.

[0]:
* run iperf
tcp connect failed: Connection refused
ERROR: iperf failed, no traffic
------------------------------------------------------------
Server listening on TCP port 5001
TCP window size:  128 KByte (default)
------------------------------------------------------------
Wait for bgs 104085
runtime: 24s
TEST FAILED

Issue: 3368293
Change-Id: I3a9b366473dfa3adcbb16bb4b247dd02b6997216
Signed-off-by: Vlad Buslov <vladbu@nvidia.com>